---

- name: Include optional user and group creation.
  include_tasks: elasticsearch-optional-user.yml
  when: (es_user_id is defined) and (es_group_id is defined)

- name: Include specific Elasticsearch
  include_tasks: elasticsearch-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Elasticsearch
  include_tasks: elasticsearch-RedHat.yml
  when: ansible_os_family == 'RedHat'
